name: pluginyay
version: 0.1.0
main: me.squirrly.pluginyay.Pluginyay
description: yes, this is meant to be a description
author: AgedSquirrel
api-version: '1.21'

commands:
  hello:
    description: Say hello to yourself (for loners)
    usage: /hello
  rpgitems:
    description: Make rpg items! (if this works) (yip yip hooray)
    usage: /rpgitems